//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMuc()
        {
            this.Hoatdongs = new HashSet<Hoatdong>();
        }
    
        public string MaThietBi { get; set; }
        public string SoSerial { get; set; }
        public string Loai { get; set; }
        public string TenThietBi { get; set; }
        public int DonGia { get; set; }
        public int SoLuong { get; set; }
        public Nullable<int> ThoiGianBaoHanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoatdong> Hoatdongs { get; set; }
        public virtual ThietBi ThietBi { get; set; }
    }
}
