//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCPT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<Hoatdong> Hoatdongs { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThietBi> ThietBis { get; set; }
    
        public virtual int sua(Nullable<int> iD, Nullable<int> sDTkhach, string tenKhachHang, string noiDungSuaChua, Nullable<System.DateTime> ngaySua, Nullable<int> chiPhi, Nullable<int> soLuong, string tenThietBi, string maThietBi, string nhanVien)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var sDTkhachParameter = sDTkhach.HasValue ?
                new ObjectParameter("SDTkhach", sDTkhach) :
                new ObjectParameter("SDTkhach", typeof(int));
    
            var tenKhachHangParameter = tenKhachHang != null ?
                new ObjectParameter("TenKhachHang", tenKhachHang) :
                new ObjectParameter("TenKhachHang", typeof(string));
    
            var noiDungSuaChuaParameter = noiDungSuaChua != null ?
                new ObjectParameter("NoiDungSuaChua", noiDungSuaChua) :
                new ObjectParameter("NoiDungSuaChua", typeof(string));
    
            var ngaySuaParameter = ngaySua.HasValue ?
                new ObjectParameter("NgaySua", ngaySua) :
                new ObjectParameter("NgaySua", typeof(System.DateTime));
    
            var chiPhiParameter = chiPhi.HasValue ?
                new ObjectParameter("ChiPhi", chiPhi) :
                new ObjectParameter("ChiPhi", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var tenThietBiParameter = tenThietBi != null ?
                new ObjectParameter("TenThietBi", tenThietBi) :
                new ObjectParameter("TenThietBi", typeof(string));
    
            var maThietBiParameter = maThietBi != null ?
                new ObjectParameter("MaThietBi", maThietBi) :
                new ObjectParameter("MaThietBi", typeof(string));
    
            var nhanVienParameter = nhanVien != null ?
                new ObjectParameter("NhanVien", nhanVien) :
                new ObjectParameter("NhanVien", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sua", iDParameter, sDTkhachParameter, tenKhachHangParameter, noiDungSuaChuaParameter, ngaySuaParameter, chiPhiParameter, soLuongParameter, tenThietBiParameter, maThietBiParameter, nhanVienParameter);
        }
    
        public virtual int Deletecell(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Deletecell", idParameter);
        }
    
        public virtual ObjectResult<Show_Result> Show(Nullable<System.DateTime> ngay)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Show_Result>("Show", ngayParameter);
        }
    
        public virtual int Them(Nullable<int> sDTkhach, string tenKhachHang, string noiDungSuaChua, Nullable<System.DateTime> ngaySua, Nullable<int> chiPhi, Nullable<int> soLuong, string tenThietBi, string maThietBi, string nhanVien)
        {
            var sDTkhachParameter = sDTkhach.HasValue ?
                new ObjectParameter("SDTkhach", sDTkhach) :
                new ObjectParameter("SDTkhach", typeof(int));
    
            var tenKhachHangParameter = tenKhachHang != null ?
                new ObjectParameter("TenKhachHang", tenKhachHang) :
                new ObjectParameter("TenKhachHang", typeof(string));
    
            var noiDungSuaChuaParameter = noiDungSuaChua != null ?
                new ObjectParameter("NoiDungSuaChua", noiDungSuaChua) :
                new ObjectParameter("NoiDungSuaChua", typeof(string));
    
            var ngaySuaParameter = ngaySua.HasValue ?
                new ObjectParameter("NgaySua", ngaySua) :
                new ObjectParameter("NgaySua", typeof(System.DateTime));
    
            var chiPhiParameter = chiPhi.HasValue ?
                new ObjectParameter("ChiPhi", chiPhi) :
                new ObjectParameter("ChiPhi", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var tenThietBiParameter = tenThietBi != null ?
                new ObjectParameter("TenThietBi", tenThietBi) :
                new ObjectParameter("TenThietBi", typeof(string));
    
            var maThietBiParameter = maThietBi != null ?
                new ObjectParameter("MaThietBi", maThietBi) :
                new ObjectParameter("MaThietBi", typeof(string));
    
            var nhanVienParameter = nhanVien != null ?
                new ObjectParameter("NhanVien", nhanVien) :
                new ObjectParameter("NhanVien", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Them", sDTkhachParameter, tenKhachHangParameter, noiDungSuaChuaParameter, ngaySuaParameter, chiPhiParameter, soLuongParameter, tenThietBiParameter, maThietBiParameter, nhanVienParameter);
        }
    
        public virtual ObjectResult<timkiem_Result> timkiem(string tim)
        {
            var timParameter = tim != null ?
                new ObjectParameter("Tim", tim) :
                new ObjectParameter("Tim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<timkiem_Result>("timkiem", timParameter);
        }
    
        public virtual int updatesoluong(string matb, Nullable<int> soluong)
        {
            var matbParameter = matb != null ?
                new ObjectParameter("Matb", matb) :
                new ObjectParameter("Matb", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updatesoluong", matbParameter, soluongParameter);
        }
    
        public virtual int SuaAcc(string userName, string passWord, string typeUser, string name)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("PassWord", passWord) :
                new ObjectParameter("PassWord", typeof(string));
    
            var typeUserParameter = typeUser != null ?
                new ObjectParameter("TypeUser", typeUser) :
                new ObjectParameter("TypeUser", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaAcc", userNameParameter, passWordParameter, typeUserParameter, nameParameter);
        }
    
        public virtual int ThemAcc(string userName, string passWord, string typeUser, string name)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("PassWord", passWord) :
                new ObjectParameter("PassWord", typeof(string));
    
            var typeUserParameter = typeUser != null ?
                new ObjectParameter("TypeUser", typeUser) :
                new ObjectParameter("TypeUser", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemAcc", userNameParameter, passWordParameter, typeUserParameter, nameParameter);
        }
    
        public virtual int XoaAcc(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaAcc", userNameParameter);
        }
    
        public virtual int SuaKH(Nullable<int> id, string ten, Nullable<int> sdt, string diachi)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var sdtParameter = sdt.HasValue ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(int));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaKH", idParameter, tenParameter, sdtParameter, diachiParameter);
        }
    
        public virtual int ThemKH(string ten, Nullable<int> sdt, string diachi)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var sdtParameter = sdt.HasValue ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(int));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemKH", tenParameter, sdtParameter, diachiParameter);
        }
    
        public virtual int XoaKH(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaKH", idParameter);
        }
    }
}
