//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoatdong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hoatdong()
        {
            this.KhachHangs = new HashSet<KhachHang>();
        }
    
        public int ID { get; set; }
        public int SDTkhach { get; set; }
        public string TenKhachHang { get; set; }
        public string NoiDungSuaChua { get; set; }
        public System.DateTime NgaySua { get; set; }
        public int ChiPhi { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string TenThietBi { get; set; }
        public string MaThietBi { get; set; }
        public string NhanVien { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
    }
}
