//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBi
    {
        public string MaThietBi { get; set; }
        public string SoSerial { get; set; }
        public string TenThietBi { get; set; }
        public Nullable<System.DateTime> NgaySX { get; set; }
        public string ThoiGianBaoHanh { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
    }
}
